# ReadThedocs hosts our Python (stacrs) documentation.

version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
    rust: "latest"
mkdocs:
  configuration: python/mkdocs.yml
python:
  install:
    - requirements: python/requirements-docs.txt
