services:
  pgstac:
    image: ghcr.io/stac-utils/pgstac:${PGSTAC_VERSION:-v0.9.6}
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
    ports:
      - "5432:5432"
    command: postgres -N 500
