site_name: stac-rs
site_description: Command Line Interface (CLI) and Rust crates the SpatioTemporal Asset Catalog (STAC) specification.
site_url: https://stac-utils.github.io/stac-rs/
repo_url: https://github.com/stac-utils/stac-rs
theme:
  name: material
  logo: img/stac-ferris.png
  icon:
    repo: fontawesome/brands/github
  favicon: img/stac-ferris-2.png
  features:
    - navigation.indexes
    - navigation.footer
  palette:
    scheme: stac
    primary: custom

nav:
  - Home: index.md
  - Command-line interface:
      - cli/index.md

plugins:
  - search
  - social:
      cards_layout_options:
        color: rgb(26, 78, 99)
        background_color: rgb(228, 246, 251)

markdown_extensions:
  - admonition

extra_css:
  - stylesheets/extra.css
