site_name: stac-rs
site_description: Command Line Interface (CLI), Rust crates, and other libraries for the SpatioTemporal Asset Catalog (STAC) specification.
site_url: https://stac-utils.github.io/stac-rs/
repo_url: https://github.com/stac-utils/stac-rs
theme:
  name: material
  logo: img/stac-ferris.png
  icon:
    repo: fontawesome/brands/github
  favicon: img/stac-ferris-2.png
  features:
    - navigation.indexes
    - navigation.footer
  palette:
    scheme: stac
    primary: custom

nav:
  - Home: index.md
  - Python:
      - python/stacrs/index.md
      - Example notebook: python/stacrs/example.ipynb
      - API:
          - python/stacrs/api/index.md
          - migrate: python/stacrs/api/migrate.md
          - read: python/stacrs/api/read.md
          - search: python/stacrs/api/search.md
          - validate: python/stacrs/api/validate.md
          - version: python/stacrs/api/version.md
          - write: python/stacrs/api/write.md
  - Command-line interface:
      - cli/index.md

plugins:
  - mike
  - mkdocs-jupyter
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          load_external_modules: false
          options:
            show_root_heading: true
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
  - search
  - social:
      cards_layout_options:
        color: rgb(26, 78, 99)
        background_color: rgb(228, 246, 251)

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css
