[workspace]
semver_check = true

[[package]]
name = "stac"

[[package]]
name = "stac-duckdb"
semver_check = false
# Until duckdb releases against the newer arrow
publish = false
git_release_enable = false

[[package]]
name = "stac-extensions"

[[package]]
name = "stac-io"

[[package]]
name = "pgstac"

[[package]]
name = "stac-server-asgi"

[[package]]
name = "stac-server"
# Until duckdb releases against the newer arrow
publish = false
git_release_enable = false

[[package]]
name = "stac-validate"

[[package]]
name = "stac-wasm"
publish = false
git_release_enable = true

[[package]]
name = "rustac"
semver_check = false
# Until duckdb releases against the newer arrow
publish = false
git_release_enable = false
