[package]
name = "stac"
version = "0.4.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
edition = "2021"
description = "Rust library for the SpatioTemporal Asset Catalog (STAC) specification"
homepage = "https://github.com/gadomski/stac-rs"
repository = "https://github.com/gadomski/stac-rs"
license = "MIT OR Apache-2.0"
keywords = ["geospatial", "stac", "metadata", "geo", "raster"]
categories = ["science", "data-structures"]

[features]
jsonschema = ["dep:jsonschema", "reqwest"]
reqwest = ["dep:reqwest"]
set_query = ["dep:serde_urlencoded"]

[dependencies]
chrono = "0.4"
geojson = "0.24"
jsonschema = { version = "0.17", optional = true, features = ["resolve-http"], default-features = false }
reqwest = { version = "0.11", optional = true, features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_urlencoded = { version = "0.7", optional = true }
thiserror = "1"
url = "2"

[dev-dependencies]
assert-json-diff = "2"

[[example]]
name = "validate"
required-features = ["jsonschema"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
