[package]
name = "pgstacrs"
edition = "2021"

[lib]
name = "pgstacrs"
crate-type = ["cdylib"]

[dependencies]
bb8.workspace = true
bb8-postgres.workspace = true
pgstac.workspace = true
pyo3.workspace = true
pyo3-async-runtimes.workspace = true
pythonize.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-postgres = { workspace = true, features = ["with-serde_json-1"] }
