[project]
name = "pgstacrs"
version = "0.1.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["pytest>=8.3.3"]

[dependency-groups]
dev = [
    "psycopg[pool]>=3.2.3",
    "pypgstac==0.8.6",
    "pytest-asyncio>=0.24.0",
    "pytest-postgresql>=6.1.1",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "module"
filterwarnings = [
    "error",
    "ignore:the default for the ConnectionPool:DeprecationWarning",
    "ignore:datetime.datetime.utcfromtimestamp:DeprecationWarning",
]

[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
