# Generated by extendr: Do not edit by hand

# nolint start

#' @docType package
#' @usage NULL
#' @useDynLib rustac, .registration = TRUE
NULL

wrap__stac_read_json <- function(path) {
  .Call("wrap__stac_read_json", path, PACKAGE = "rustac")
}

wrap__stac_write_json <- function(json, path) {
  .Call("wrap__stac_write_json", json, path, PACKAGE = "rustac")
}

wrap__stac_read_geoparquet <- function(path) {
  .Call("wrap__stac_read_geoparquet", path, PACKAGE = "rustac")
}

wrap__stac_write_geoparquet <- function(ipc_bytes, path) {
  .Call("wrap__stac_write_geoparquet", ipc_bytes, path, PACKAGE = "rustac")
}

# nolint end
