[package]
name = "duckdb-test"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
