[package]
name = "stac-duckdb"
version = "0.1.0"
edition = "2021"

[features]
bundled = ["duckdb/bundled"]

[dependencies]
arrow = "52"
duckdb = "1"
geoarrow = { version = "0.3.0-beta.3" }
parquet = "52"
stac = { version = "0.8", path = "../core", features = ["geoarrow"] }
stac-api = { version = "0.4", path = "../api" }
thiserror = "1"

[dev-dependencies]
duckdb-test = { path = "duckdb-test" }
geo = "0.28"
