[package]
name = "stac-duckdb"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "52"
duckdb = "1"
geoarrow = { git = "https://github.com/geoarrow/geoarrow-rs", rev = "6b877486bf98f280bc04b589eb7ce25b20e629f0" }
parquet = "52"
stac = { version = "0.8", path = "../core", features = ["geoarrow"] }
stac-api = { version = "0.4", path = "../api" }
thiserror = "1"

[dev-dependencies]
duckdb-test = { path = "duckdb-test" }
geo = "0.28"
