[package]
name = "python"
description = "Python bindings for stac-rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stac-utils/stac-rs"
homepage = "https://github.com/stac-utils/stac-rs"
version = "0.0.3"
edition = "2021"
publish = false

[lib]
name = "stacrs"
crate-type = ["cdylib"]

[features]
geoparquet = ["stac/geoparquet-compression"]

[dependencies]
geojson = "0.24"
pyo3 = "0.22"
pythonize = "0.22"
serde = "1"
serde_json = "1"
stac = { path = "../core", features = ["reqwest", "object-store-all"] }
stac-api = { path = "../api", features = ["client"] }
stac-validate = { path = "../validate", features = ["blocking"] }
tokio = { version = "1", features = ["rt"] }
