[package]
name = "python"
description = "Python bindings for stac-rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stac-utils/stac-rs"
homepage = "https://github.com/stac-utils/stac-rs"
version = "0.1.2"
edition = "2021"
publish = false

[lib]
name = "stacrs"
crate-type = ["cdylib"]

[dependencies]
geojson = "0.24"
pyo3 = { version = "0.22", features = ["extension-module"] }
pythonize = "0.22"
serde = "1"
serde_json = "1"
stac = { path = "../core", features = [
    "geoparquet-compression",
    "object-store-all",
    "reqwest",
    "validate-blocking",
] }
stac-api = { path = "../api", features = ["client"] }
tokio = { version = "1", features = ["rt"] }
