[package]
name = "python"
description = "Python bindings for stac-rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stac-utils/stac-rs"
homepage = "https://github.com/stac-utils/stac-rs"
version = "0.0.2"
edition = "2021"
publish = false

[lib]
name = "stacrs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22"
pythonize = "0.22"
stac = { version = "0.8", path = "../stac", features = ["reqwest"] }
stac-validate = { version = "0.2", path = "../stac-validate" }
