[package]
name = "python"
description = "Python bindings for stac-rs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/stac-utils/stac-rs"
homepage = "https://github.com/stac-utils/stac-rs"
version = "0.0.3"
edition = "2021"
publish = false

[lib]
name = "stacrs"
crate-type = ["cdylib"]

[dependencies]
clap = "4"
pyo3 = "0.22"
pythonize = "0.22"
stac = { path = "../core", features = ["reqwest"] }
stac-cli = { path = "../cli", default-features = false }
stac-validate = { path = "../validate" }
tokio = { version = "1", features = ["rt-multi-thread"] }
