site_name: stacrs
site_url: https://stacrs.readthedocs.org
repo_url: https://github.com/stac-utils/stac-rs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
nav:
  - Home: index.md
  - API:
      - api/index.md
      - migrate: api/migrate.md
      - read: api/read.md
      - search: api/search.md
      - validate: api/validate.md
      - write: api/write.md
      - pystac: api/pystac.md
plugins:
  - search
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          load_external_modules: false
          options:
            show_root_heading: true
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
