[package]
name = "duckdb-test"
version = "0.0.0"
edition.workspace = true
publish = false

[lib]
proc-macro = true
test = false
doctest = false

[dependencies]
quote.workspace = true
syn = { workspace = true, features = ["full", "extra-traits"] }
