name: Api

on:
  pull_request:
    paths:
      - api/**
  push:
    paths:
      - api/**
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: api

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  test-api:
    strategy:
      matrix: 
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo check
      - name: Check w/ geo
        run: cargo check -F geo
      - name: Check w/ client
        run: cargo check -F client
      - name: Test
        run: cargo test --all-features
