name: CD

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    env:
      GIT_COMMITTER_NAME: ci-bot
      GIT_COMMITTER_EMAIL: ci-bot@example.com
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Sync
        run: uv sync --group docs
      - name: Build
        run: uv run mkdocs build
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: site/
  deploy-docs:
    needs: build-docs
    name: Deploy docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Test w/ coverage
        run: cargo tarpaulin -p stac -p stac-api --all-features --out xml
      - uses: codecov/codecov-action@v5
        with:
          files: ./cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
