name: Cli

on:
  pull_request:
    paths:
      - cli/**
  push:
    branches:
      - main
    paths:
      - cli/**
  workflow_dispatch:

defaults:
  run:
    working-directory: cli

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  test-cli:
    strategy:
      matrix: 
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Check w/ no default features
        run: cargo check --no-default-features
      - name: Check w/ pgstac
        run: cargo check --no-default-features -F pgstac
      - name: Check w/ python
        run: cargo check --no-default-features -F python
      - name: Test
        run: cargo test --no-default-features -F pgstac -F python
  test-cli-with-gdal:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        args:
          - "--no-default-features -F gdal"
          - ""
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install libgdal-dev
      - name: Test
        run: cargo test ${{ matrix.args }}
  test-cli-with-duckdb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --no-default-features -F duckdb -F duckdb/bundled
