name: cli

on:
  pull_request:
    paths:
      - cli/**
  workflow_dispatch:

defaults:
  run:
    working-directory: cli

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  test:
    strategy:
      matrix: 
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        args:
          - "--no-default-features"
          - "--no-default-features -F geoparquet"
          - "--no-default-features -F pgstac"
          - "--no-default-features -F python"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test ${{ matrix.args }}
  test-with-gdal:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        args:
          - "--no-default-features -F gdal"
          - ""
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install libgdal-dev
      - name: Test
        run: cargo test ${{ matrix.args }}
