name: Core

on:
  pull_request:
    paths:
      - core/**
  push:
    branches:
      - main
    paths:
      - core/**
  workflow_dispatch:
defaults:
  run:
    working-directory: core

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  test-core:
    strategy:
      matrix: 
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo check
      - name: Check w/ geo
        run: cargo check -F geo
      - name: Check w/ geoarrow
        run: cargo check -F geoarrow
      - name: Check w/ geoparquet
        run: cargo check -F geoparquet
      - name: Check w/ object-store
        run: cargo check -F object-store
      - name: Check w/ reqwest
        run: cargo check -F reqwest
      - name: Test
        run: cargo test -F geo -F geoparquet-compression -F reqwest -F object-store-all
  test-core-with-gdal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install libgdal-dev
      - name: Test
        run: cargo test -F gdal
