name: Labels

on:
  pull_request:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-bundled-duckdb:
    name: Build w/ bundled DuckDB
    if: ${{ github.event.label.name == '[build] bundled-duckdb' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build -p stac-cli -F duckdb-bundled
      - name: Test
        run: cargo test -p stac-cli -F duckdb-bundled
