name: pgstac

on:
  pull_request:
    paths:
      - pgstac/**
  workflow_dispatch:

defaults:
  run:
    working-directory: pgstac

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      pgstac:
        image: ghcr.io/stac-utils/pgstac:v0.8.6
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgis
          PGUSER: username
          PGPASSWORD: password
          PGDATABASE: postgis
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test
