name: Release npm

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    if: startsWith(github.event.release.name, 'stac-wasm-v')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crates/wasm
    environment:
      name: npm
      url: https://www.npmjs.com/package/stac-wasm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cargo-bins/cargo-binstall@0b24824336e2b3800b0f89d9e08b2c08bfa3dcdd # v1.17.9
      - name: Install wasm-pack
        run: cargo binstall wasm-pack --no-confirm
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Build wasm
        run: wasm-pack build
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - name: Publish to npm
        run: npm publish ./pkg --provenance --access public
