name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  x84_64-apple-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -p stac-cli --release --all-features
      - name: Archive
        run: |
          ARCHIVE_FILE=stac-x86_64-apple-darwin.tar.gz
          tar czvf $ARCHIVE_FILE -C target/release stac
          shasum -a 256 $ARCHIVE_FILE > $ARCHIVE_FILE.sha256
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            *.tar.gz
            *.sha256

  release:
    runs-on: ubuntu-latest
    needs:
      - x84_64-apple-darwin
    if: "startsWith(github.ref, 'refs/tags/stac-cli')"
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: binaries
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: binaries/*
