name: Release-plz

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  DUCKDB_VERSION: "1.4.2"
  DUCKDB_LIB_DIR: /opt/duckdb
  LD_LIBRARY_PATH: /opt/duckdb

jobs:
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false
      - &generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ vars.RELEASE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
      - name: Get DuckDB
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v${{ env.DUCKDB_VERSION }}/libduckdb-linux-amd64.zip
          unzip libduckdb-linux-amd64.zip -d /opt/duckdb
          rm libduckdb-linux-amd64.zip
      - name: Run release-plz
        uses: release-plz/action@064f4d1e36c843611ddf013be726beaa4ad804db # v0.5.129
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - *checkout
      - *generate-token
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Run release-plz
        uses: release-plz/action@064f4d1e36c843611ddf013be726beaa4ad804db # v0.5.129
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
